apiVersion: v1
kind: Service
metadata:
  name: __projectName__-service
spec:
  selector:
    app: __projectName__
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer
