#!/bin/sh -e
# ============================================
#  drups - Starts the Drups worker daemon.
# ============================================
#
# This file is part of the Drups.io Engine.
#
# (c) 2021 Drups.io <dev@drups.io>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# Written by Temuri Takalandze <temo@drups.io>, March 2021
#
# :Usage: /etc/init.d/drups {start|stop|restart|graceful|kill|dryrun|create-paths}
# :Configuration file: /etc/default/drups (or /usr/local/etc/drups on BSD)

### BEGIN INIT INFO
# Provides:          drups
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: drups task worker daemon
### END INIT INFO
#
#
# To implement separate init-scripts, copy this script and give it a different
# name.  That is, if your new application named "little-worker" needs an init,
# you should use:
#
#   cp /etc/init.d/drups /etc/init.d/little-worker
#
# You can then configure this by manipulating /etc/default/little-worker.
#

if [ $(id -u) -ne 0 ]; then
    echo "Error: drupsd can only be used by the root user."
    exit 1
fi

origin_is_runlevel_dir () {
    set +e
    dirname $0 | grep -q "/etc/rc.\.d"
    echo $?
}

# Can be a runlevel symlink (e.g., S02drups)
if [ $(origin_is_runlevel_dir) -eq 0 ]; then
    SCRIPT_FILE=$(readlink "$0")
else
    SCRIPT_FILE="$0"
fi
SCRIPT_NAME="$(basename "$SCRIPT_FILE")"

DEFAULT_USER="drups"
DEFAULT_PID_FILE="/var/run/drups/%n.pid"
DEFAULT_LOG_FILE="/var/log/drups/%n%I.log"
DEFAULT_LOG_LEVEL="INFO"
DEFAULT_NODES="drups"

DRUPS_APP_ARG="--app=drups"

if [ -d "/etc/default" ]; then
	DRUPS_CONFIG_DIR="/etc/default"
else
	DRUPS_CONFIG_DIR="/usr/local/etc"
fi

DRUPS_DEFAULTS=${DRUPS_DEFAULTS:-"$DRUPS_CONFIG_DIR/${SCRIPT_NAME}"}

# Make sure executable configuration script is owned by root
_config_sanity() {
    local path="$1"
    local owner=$(ls -ld "$path" | awk '{print $3}')
    local iwgrp=$(ls -ld "$path" | cut -b 6)
    local iwoth=$(ls -ld "$path" | cut -b 9)

    if [ "$(id -u $owner)" != "0" ]; then
        echo "Error: Config script '$path' must be owned by root!"
        echo
        echo "Resolution:"
        echo "Review the file carefully, and make sure it hasn't been "
        echo "modified with mailicious intent.  When sure the "
        echo "script is safe to execute with superuser privileges "
        echo "you can change ownership of the script:"
        echo "    $ sudo chown root '$path'"
        exit 1
    fi

    if [ "$iwoth" != "-" ]; then  # S_IWOTH
        echo "Error: Config script '$path' cannot be writable by others!"
        echo
        echo "Resolution:"
        echo "Review the file carefully, and make sure it hasn't been "
        echo "modified with malicious intent.  When sure the "
        echo "script is safe to execute with superuser privileges "
        echo "you can change the scripts permissions:"
        echo "    $ sudo chmod 640 '$path'"
        exit 1
    fi

    if [ "$iwgrp" != "-" ]; then  # S_IWGRP
        echo "Error: Config script '$path' cannot be writable by group!"
        echo
        echo "Resolution:"
        echo "Review the file carefully, and make sure it hasn't been "
        echo "modified with malicious intent.  When sure the "
        echo "script is safe to execute with superuser privileges "
        echo "you can change the scripts permissions:"
        echo "    $ sudo chmod 640 '$path'"
        exit 1
    fi
}

if [ -f "$DRUPS_DEFAULTS" ]; then
    _config_sanity "$DRUPS_DEFAULTS"
    echo "Using config script: $DRUPS_DEFAULTS"
    . "$DRUPS_DEFAULTS"
fi

# Options to su
# can be used to enable login shell (DRUPSD_SU_ARGS="-l"),
# or even to use start-stop-daemon instead of su.
DRUPSD_SU=${DRUPS_SU:-"su"}
DRUPSD_SU_ARGS=${DRUPSD_SU_ARGS:-""}

DRUPSD_USER=${DRUPSD_USER:-$DEFAULT_USER}

# Set DRUPS_CREATE_DIRS to always create log/pid dirs.
DRUPS_CREATE_DIRS=${DRUPS_CREATE_DIRS:-0}
DRUPS_CREATE_RUNDIR=$DRUPS_CREATE_DIRS
DRUPS_CREATE_LOGDIR=$DRUPS_CREATE_DIRS
if [ -z "$DRUPSD_PID_FILE" ]; then
    DRUPSD_PID_FILE="$DEFAULT_PID_FILE"
    DRUPS_CREATE_RUNDIR=1
fi
if [ -z "$DRUPSD_LOG_FILE" ]; then
    DRUPSD_LOG_FILE="$DEFAULT_LOG_FILE"
    DRUPS_CREATE_LOGDIR=1
fi

DRUPSD_LOG_LEVEL=${DRUPSD_LOG_LEVEL:-${DRUPSD_LOGLEVEL:-$DEFAULT_LOG_LEVEL}}
DRUPS_BIN=${DRUPS_BIN:-"drups"}
DRUPSD_MULTI=${DRUPSD_MULTI:-"$DRUPS_BIN multi"}
DRUPSD_NODES=${DRUPSD_NODES:-$DEFAULT_NODES}

export DRUPS_LOADER

if [ -n "$2" ]; then
    DRUPSD_OPTS="$DRUPSD_OPTS $2"
fi

DRUPSD_LOG_DIR=`dirname $DRUPSD_LOG_FILE`
DRUPSD_PID_DIR=`dirname $DRUPSD_PID_FILE`

# Extra start-stop-daemon options, like user/group.
if [ -n "$DRUPSD_CHDIR" ]; then
    DAEMON_OPTS="$DAEMON_OPTS --workdir=$DRUPSD_CHDIR"
fi

check_dev_null() {
    if [ ! -c /dev/null ]; then
        echo "/dev/null is not a character device!"
        exit 75  # EX_TEMPFAIL
    fi
}

maybe_die() {
    if [ $? -ne 0 ]; then
        echo "Exiting: $* (errno $?)"
        exit 77  # EX_NOPERM
    fi
}

create_default_dir() {
    if [ ! -d "$1" ]; then
        echo "- Creating default directory: '$1'"
        mkdir -p "$1"
        maybe_die "Couldn't create directory $1"
        echo "- Changing permissions of '$1' to 02755"
        chmod 02755 "$1"
        maybe_die "Couldn't change permissions for $1"
        if [ -n "$DRUPSD_USER" ]; then
            echo "- Changing owner of '$1' to '$DRUPSD_USER'"
            chown "$DRUPSD_USER" "$1"
            maybe_die "Couldn't change owner of $1"
        fi
        if [ -n "$DRUPSD_GROUP" ]; then
            echo "- Changing group of '$1' to '$DRUPSD_GROUP'"
            chgrp "$DRUPSD_GROUP" "$1"
            maybe_die "Couldn't change group of $1"
        fi
    fi
}

check_paths() {
    if [ $DRUPS_CREATE_LOGDIR -eq 1 ]; then
        create_default_dir "$DRUPSD_LOG_DIR"
    fi
    if [ $DRUPS_CREATE_RUNDIR -eq 1 ]; then
        create_default_dir "$DRUPSD_PID_DIR"
    fi
}

create_paths() {
    create_default_dir "$DRUPSD_LOG_DIR"
    create_default_dir "$DRUPSD_PID_DIR"
}

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

_get_pidfiles () {
    # note: multi < 3.1.14 output to stderr, not stdout, hence the redirect.
    ${DRUPSD_MULTI} expand "${DRUPSD_PID_FILE}" ${DRUPSD_NODES} 2>&1
}

_get_pids() {
    found_pids=0
    my_exitcode=0

    for pidfile in $(_get_pidfiles); do
        local pid=`cat "$pidfile"`
        local cleaned_pid=`echo "$pid" | sed -e 's/[^0-9]//g'`
        if [ -z "$pid" ] || [ "$cleaned_pid" != "$pid" ]; then
            echo "bad pid file ($pidfile)"
            one_failed=true
            my_exitcode=1
        else
            found_pids=1
            echo "$pid"
        fi

    if [ $found_pids -eq 0 ]; then
        echo "${SCRIPT_NAME}: All nodes down"
        exit $my_exitcode
    fi
    done
}

_chuid () {
    ${DRUPSD_SU} ${DRUPSD_SU_ARGS} "$DRUPSD_USER" -c "$DRUPSD_MULTI $*"
}

start_workers () {
    if [ ! -z "$DRUPSD_ULIMIT" ]; then
        ulimit $DRUPSD_ULIMIT
    fi
    _chuid $* start $DRUPSD_NODES $DAEMON_OPTS     \
                 --pidfile="$DRUPSD_PID_FILE"      \
                 --logfile="$DRUPSD_LOG_FILE"      \
                 --loglevel="$DRUPSD_LOG_LEVEL"    \
                 $DRUPS_APP_ARG                    \
                 $DRUPSD_OPTS
}

dryrun () {
    (C_FAKEFORK=1 start_workers --verbose)
}

stop_workers () {
    _chuid stopwait $DRUPSD_NODES $DAEMON_OPTS --pidfile="$DRUPSD_PID_FILE"
}

restart_workers () {
    _chuid restart $DRUPSD_NODES $DAEMON_OPTS      \
                   --pidfile="$DRUPSD_PID_FILE"    \
                   --logfile="$DRUPSD_LOG_FILE"    \
                   --loglevel="$DRUPSD_LOG_LEVEL"  \
                   $DRUPS_APP_ARG                  \
                   $DRUPSD_OPTS
}

kill_workers() {
    _chuid kill $DRUPSD_NODES $DAEMON_OPTS --pidfile="$DRUPSD_PID_FILE"
}

restart_workers_graceful () {
    echo "WARNING: Use with caution in production"
    echo "The workers will attempt to restart, but they may not be able to."
    local worker_pids=
    worker_pids=`_get_pids`
    [ "$one_failed" ] && exit 1

    for worker_pid in $worker_pids; do
        local failed=
        kill -HUP $worker_pid 2> /dev/null || failed=true
        if [ "$failed" ]; then
            echo "${SCRIPT_NAME} worker (pid $worker_pid) could not be restarted"
            one_failed=true
        else
            echo "${SCRIPT_NAME} worker (pid $worker_pid) received SIGHUP"
        fi
    done

    [ "$one_failed" ] && exit 1 || exit 0
}

check_status () {
    my_exitcode=0
    found_pids=0

    local one_failed=
    for pidfile in $(_get_pidfiles); do
        if [ ! -r $pidfile ]; then
            echo "${SCRIPT_NAME} down: no pidfiles found"
            one_failed=true
            break
        fi

        local node=`basename "$pidfile" .pid`
        local pid=`cat "$pidfile"`
        local cleaned_pid=`echo "$pid" | sed -e 's/[^0-9]//g'`
        if [ -z "$pid" ] || [ "$cleaned_pid" != "$pid" ]; then
            echo "bad pid file ($pidfile)"
            one_failed=true
        else
            local failed=
            kill -0 $pid 2> /dev/null || failed=true
            if [ "$failed" ]; then
                echo "${SCRIPT_NAME} (node $node) (pid $pid) is down, but pidfile exists!"
                one_failed=true
            else
                echo "${SCRIPT_NAME} (node $node) (pid $pid) is up..."
            fi
        fi
    done

    [ "$one_failed" ] && exit 1 || exit 0
}

case "$1" in
    start)
        check_dev_null
        check_paths
        start_workers
    ;;

    stop)
        check_dev_null
        check_paths
        stop_workers
    ;;

    reload|force-reload)
        echo "Use restart"
    ;;

    status)
        check_status
    ;;

    restart)
        check_dev_null
        check_paths
        restart_workers
    ;;

    graceful)
        check_dev_null
        restart_workers_graceful
    ;;

    kill)
        check_dev_null
        kill_workers
    ;;

    dryrun)
        check_dev_null
        dryrun
    ;;

    try-restart)
        check_dev_null
        check_paths
        restart_workers
    ;;

    create-paths)
        check_dev_null
        create_paths
    ;;

    check-paths)
        check_dev_null
        check_paths
    ;;

    *)
        echo "Usage: /etc/init.d/${SCRIPT_NAME} {start|stop|restart|graceful|kill|dryrun|create-paths}"
        exit 64  # EX_USAGE
    ;;
esac

exit 0
